### ISSUE TITLE
How to use locally

### ISSUE THREAD

**Issue by euglv** [technicallyjosh/pino-http-send#4]
Does not work when installed locally using `npm i pino-http-send`
Gives the following error on RHEL7:
`bash: pino-http-send: command not found`
And the following on Windows:
```
'pino-http-send' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by euglv** [comment]
To use locally with piping:
`node . | node ./node_modules/pino-http-send/ --url=http://localhost:8080/`

**Comment by technicallyjosh** [comment]
Because when you install locally, that .bin folder is not part of your path. For it to be available in your path you have to install it globally using the `-g` flag. I'd suggest using it in an npm script witch can access the local path of the executable.

e.g. a package.json file
```json
{
  "scripts": {
    "start": "node . | pino-http-send --url=http://localhost:8080"
  }
}
```

...by using it in the context of an NPM script, it will check `./node_modules/.bin` and then check globally in your path.

**Comment by technicallyjosh** [comment]
You can also refer to https://nodejs.org/en/blog/npm/npm-1-0-global-vs-local-installation/ for basic module installation information.
